name: "Build"
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v14
      with:
        extra_nix_config: |
          trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
          substituters = https://hydra.iohk.io https://cache.nixos.org/

    - uses: cachix/cachix-action@v10
      with:
        name: tweag-haskell-fido2
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: "Stylecheck"
      run: |
        nix-shell --pure --command ./bin/autoformat.sh
        git diff --exit-code

    - name: "Build"
      run: nix-build -A fido2.checks
